Global:
  character_dict_path: configs/ppocr_keys_v1.txt
  character_type: ch
  use_space_char: True
  max_text_length: 25
  infer_img: null
  pretrained_model: ./openocr_repsvtr_ch.pth
  checkpoints: null
  output_dir: ./output/rec/iiit5k
  save_epoch_step: 1
  eval_batch_step: [0, 1000]
  cal_metric_during_train: True
  use_visualdl: False
  print_batch_step: 10
  epochs: 20
  eval_epoch: 1
  pretrained: True
  save_inference_dir: null
  use_gpu: True
  distributed: True

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./data/IIIT5K
    label_file_list: ["./data/IIIT5K/rec_gt_train.txt"]
    transforms:
      - DecodeImage: {img_mode: RGB, channel_first: False}
      - RecResizeImg: {image_shape: [3, 32, 100]}
      - CTCLabelEncode: {}
      - KeepKeys: {keep_keys: ['image', 'label']}
  loader:
    shuffle: True
    batch_size_per_card: 64
    drop_last: True
    num_workers: 4

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./data/IIIT5K
    label_file_list: ["./data/IIIT5K/rec_gt_test.txt"]
    transforms:
      - DecodeImage: {img_mode: RGB, channel_first: False}
      - RecResizeImg: {image_shape: [3, 32, 100]}
      - CTCLabelEncode: {}
      - KeepKeys: {keep_keys: ['image', 'label']}
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 64
    num_workers: 4

Architecture:
  model_type: rec
  algorithm: SVTR
  Transform: null
  Backbone:
    name: SVTRNet
    img_size: [32, 100]
    out_char_num: 25
  Head:
    name: CTCHead
    fc_decay: 0.00001

Loss:
  name: CTCLoss

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999

LRScheduler:
  name: Cosine
  learning_rate: 0.0005
  warmup_epoch: 2
